name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
      - name: test
        run: go test -v ./...
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  homebrew:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - name: update homebrew tap
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          homebrew-tap: cuotos/homebrew-tap
          download-url: https://github.com/cuotos/sts-assume-role-env-vars/releases/download/${{ steps.extract-version.outputs.tag-name }}/sts-assume-role-env-vars_${{ steps.extract-version.outputs.tag-name }}_Darwin_x86_64.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}